export const UNIVERSITY_INFO = {
  name: "Trường Đại học Công Nghệ & Tuyển Sinh 2026",
  shortName: "TFT Academy",
  hotline: "1900 6868",
  email: "tuyensinh@admission.edu.vn",
  address: "Số 28A Lê Trọng Tấn, Hà Đông, Hà Nội",
  website: "https://tuyensinh.edu.vn",
  admissionYear: 2026,
};

export const INITIAL_COURSES = [
  {
    id: "c1",
    code: "7480201",
    name: "Công nghệ Thông tin",
    faculty: "Khoa Công nghệ Thông tin",
    quota: 450,
    tuitionPerTerm: 18500000,
    durationYears: 4,
    subjectGroups: ["A00", "A01", "D01", "D07"],
    previousCutoffScore: 25.75,
    description: "Chương trình định hướng Kỹ thuật phần mềm, Trí tuệ nhân tạo, An ninh mạng chuẩn quốc tế.",
    careerOpportunities: ["Kỹ sư phần mềm", "Chuyên viên bảo mật", "Kỹ sư dữ liệu", "Quản lý dự án CNTT"],
  },
  {
    id: "c2",
    code: "7480107",
    name: "Trí tuệ Nhân tạo (AI & Data Science)",
    faculty: "Khoa Công nghệ Thông tin",
    quota: 200,
    tuitionPerTerm: 21000000,
    durationYears: 4,
    subjectGroups: ["A00", "A01", "D07"],
    previousCutoffScore: 26.5,
    description: "Đào tạo chuyên sâu về Machine Learning, Deep Learning, Xử lý ngôn ngữ tự nhiên và Thị giác máy tính.",
    careerOpportunities: ["AI Engineer", "Data Scientist", "Machine Learning Researcher", "Robotics Specialist"],
  },
  {
    id: "c3",
    code: "7340101",
    name: "Quản trị Kinh doanh",
    faculty: "Khoa Kinh tế & Quản trị",
    quota: 380,
    tuitionPerTerm: 16500000,
    durationYears: 4,
    subjectGroups: ["A01", "D01", "D07", "C00"],
    previousCutoffScore: 24.2,
    description: "Trang bị tư duy chiến lược, khởi nghiệp đổi mới sáng tạo, quản trị chuỗi cung ứng toàn cầu.",
    careerOpportunities: ["Giám đốc kinh doanh", "Chuyên viên phân tích thị trường", "Quản lý vận hành", "Nhà khởi nghiệp"],
  },
  {
    id: "c4",
    code: "7340115",
    name: "Digital Marketing (Marketing Số)",
    faculty: "Khoa Kinh tế & Quản trị",
    quota: 250,
    tuitionPerTerm: 17500000,
    durationYears: 4,
    subjectGroups: ["A01", "D01", "D07", "D14"],
    previousCutoffScore: 25.1,
    description: "Thực chiến Content Marketing, SEO/SEM, Social Media Analytics, Brand Communication trên nền tảng số.",
    careerOpportunities: ["Growth Marketer", "Digital Marketing Specialist", "Brand Strategist", "Media Planner"],
  },
  {
    id: "c5",
    code: "7210403",
    name: "Thiết kế Đồ họa & Truyền thông Đa phương tiện",
    faculty: "Khoa Mỹ thuật Ứng dụng",
    quota: 220,
    tuitionPerTerm: 19000000,
    durationYears: 4,
    subjectGroups: ["H00", "H01", "V00", "D01"],
    previousCutoffScore: 23.8,
    description: "Đào tạo mỹ thuật số, UI/UX Design, 3D Animation, Kỹ xảo điện ảnh và xây dựng bộ nhận diện thương hiệu.",
    careerOpportunities: ["UI/UX Designer", "Motion Graphic Artist", "Art Director", "Concept Artist"],
  },
  {
    id: "c6",
    code: "7220201",
    name: "Ngôn ngữ Anh (Biên phiên dịch & Thương mại)",
    faculty: "Khoa Ngoại ngữ",
    quota: 300,
    tuitionPerTerm: 15500000,
    durationYears: 4,
    subjectGroups: ["D01", "D07", "D14", "D15"],
    previousCutoffScore: 24.5,
    description: "Chuẩn đầu ra IELTS 7.0+, ứng dụng tiếng Anh trong ngoại giao, xuất nhập khẩu và kinh doanh quốc tế.",
    careerOpportunities: ["Biên phiên dịch viên", "Chuyên viên đối ngoại", "Giảng viên tiếng Anh", "Chuyên viên PR"],
  },
];

export const CHATBOT_KNOWLEDGE = [
  {
    keywords: ["học phí", "chi phí", "bao nhiêu tiền", "tiền học", "kỳ"],
    answer: "Học phí trung bình tại trường dao động từ 15.500.000đ - 21.000.000đ / học kỳ tùy theo ngành đào tạo:\n- Ngôn ngữ Anh: 15.5 triệu/kỳ\n- Quản trị Kinh doanh: 16.5 triệu/kỳ\n- Digital Marketing: 17.5 triệu/kỳ\n- CNTT & Kỹ thuật phần mềm: 18.5 triệu/kỳ\n- Trí tuệ Nhân tạo (AI): 21 triệu/kỳ.\nTrường cam kết không tăng học phí quá 8%/năm và hỗ trợ trả góp 0% lãi suất qua các ngân hàng liên kết.",
    suggested: ["Chính sách học bổng", "Thời hạn nộp học bạ", "Xét tuyển ngành CNTT"],
  },
  {
    keywords: ["học bổng", "ưu đãi", "miễn giảm", "tài trợ"],
    answer: "Trường dành quỹ học bổng tuyển sinh 30 TỶ ĐỒNG cho tân sinh viên năm 2026:\n1. Học bổng Tài năng (100% học phí toàn khóa): Thí sinh đạt giải HSG Quốc gia hoặc điểm THPT từ 28.0+.\n2. Học bổng Khuyến khích (50% học phí năm 1): Điểm thi THPT từ 26.0 - 27.99 hoặc IELTS 7.5+.\n3. Học bổng Thủ khoa ngành (100% học phí năm 1).\n4. Học bổng Tân sinh viên nộp sớm (Giảm 5 triệu đồng lệ phí nhập học).",
    suggested: ["Học bạ cần bao nhiêu điểm?", "Hồ sơ xét tuyển gồm những gì?", "Đăng ký tư vấn trực tiếp"],
  },
  {
    keywords: ["điểm chuẩn", "điểm trúng tuyển", "bao nhiêu điểm", "lấy bao nhiêu"],
    answer: "Điểm chuẩn tham khảo năm trước (theo điểm thi THPT thang 30):\n- Trí tuệ nhân tạo (AI): 26.5 điểm\n- Công nghệ Thông tin: 25.75 điểm\n- Digital Marketing: 25.10 điểm\n- Ngôn ngữ Anh: 24.50 điểm\n- Quản trị Kinh doanh: 24.20 điểm\n- Thiết kế Đồ họa: 23.80 điểm.\nVới phương thức Xét học bạ THPT, điểm nhận hồ sơ từ 20.0 điểm cho tổ hợp 3 môn học kỳ 1 lớp 12 hoặc 3 học kỳ.",
    suggested: ["Cách tính điểm học bạ", "Ngành CNTT học những gì?", "Hạn chót nộp hồ sơ"],
  },
  {
    keywords: ["hồ sơ", "thủ tục", "cần giấy tờ gì", "cách đăng ký", "nộp hồ sơ"],
    answer: "Hồ sơ xét tuyển trực tuyến bao gồm:\n1. Phiếu đăng ký xét tuyển (điền online trên hệ thống)\n2. Bản chụp/photo công chứng Học bạ THPT\n3. Bản photo CCCD/Hộ chiếu\n4. Giấy chứng nhận tốt nghiệp THPT tạm thời (bổ sung sau khi thi)\n5. Chứng chỉ ngoại ngữ quốc tế (IELTS/TOEFL) nếu có để cộng điểm ưu tiên.\nThí sinh có thể nộp hồ sơ online trực tiếp trên website ngay hôm nay!",
    suggested: ["Đăng ký xét tuyển ngay", "Học phí ngành AI", "Ký túc xá của trường"],
  },
  {
    keywords: ["ký túc xá", "chỗ ở", "ktx", "ở đâu"],
    answer: "Trường có khu Ký túc xá hiện đại nằm ngay trong khuôn viên với sức chứa 3.000 sinh viên. Trang bị đầy đủ điều hòa, bình nóng lạnh, wifi tốc độ cao, phòng tự học và khu thể thao phức hợp. Chi phí chỉ từ 650.000đ - 1.200.000đ/tháng tùy loại phòng (4-6 người/phòng). Ưu tiên 100% cho tân sinh viên ngoại tỉnh nộp hồ sơ sớm.",
    suggested: ["Học phí các ngành", "Hồ sơ nhập học", "Liên hệ cán bộ tuyển sinh"],
  },
];
